### ISSUE TITLE
Please specify Unity version with which this code is compatible

### ISSUE THREAD

**Issue by Rubix1991** [Unity-Technologies/ui-toolkit-manual-code-examples#7]
Could you add Unity version which is compatible with this code in Readme.md, since for ex., this code doesn't compile with 2020.3.

For ex.,
Assets\create-listviews-treeviews\PlanetsWindow.cs(110,28): error CS0246: The type or namespace name 'TreeViewItemData<>' could not be found (are you missing a using directive or an assembly reference?)

**Comment by lilisha-unity** [comment]
Thanks for your feedback. We've added a version number to the individual tutorial page for the newly added doc, and will add the verison to the existing docs too.

**Comment by Rubix1991** [comment]
thx
